# Generated by Django 4.0.2 on 2022-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_redirect_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='redirect_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Redirect URL'),
        ),
    ]
