# Generated by Django 4.0.2 on 2022-02-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_alter_survey_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='session_key',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
