# Generated by Django 4.0.2 on 2022-02-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_response_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='session_key',
            new_name='django_session_key',
        ),
    ]
