# Generated by Django 4.0.2 on 2022-06-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_survey_private_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='django_session_key',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
